- README.md
- check.py
The package ID should be unique in the file. The checksum does not need to be unique and is currently not unique in the tsv file. This is because of different packages referring to one tarball. If we want, we can get rid of this.
Depending on the [naming schema](https://github.com/erasche/community-package-cache/issues/3) we might change this constraint to column1+column3. So that we explicitly allow the same package name if it has a different architecture.
> add unique constraint

- urls.tsv
This PR adds a reference to a patched version of the `numpy 1.9.2` source.
The patch creates a `site.cfg` file when `setup.py` is run, which explicitly specifies the ATLAS libraries from `package_atlas_3_10` (using the environment variables set by that package).
This new `numpy` package is needed for this proposed fix to `package_python_2_7_numpy_1_9`:
https://github.com/galaxyproject/tools-iuc/pull/547
> Add patched numpy 1.9.2 to explicitly use Galaxy ATLAS

- urls.tsv
Edger 3.12 requires a version of limma >= 3.25.6 as it uses the kegga function.
Here is the latest limma version
> add a newer limma package

- bin/gsl.py
- urls.tsv
This build will fail.
It is because we do terrible things in our `.ci` script. That should be fixed eventually to use the cargo-port built in tools which escape things properly. For now we're pushing this through. #73 will track the CI crap bug.
> Fix #71 fail

- urls.tsv
This is no longer on the SourceForge page, sadly. Using Dropbox as short term solution to getting the file into the cache.
Originally at:
http://downloads.sourceforge.net/project/mira-assembler/MIRA/development/mira_4.9.5_2_linux-gnu_x86_64_static.tar.bz2
See also:
https://github.com/peterjc/galaxy_mira/blob/master/packages/package_mira_4_9_5/tool_dependencies.xml
See mailing list discussion:
https://lists.galaxyproject.org/pipermail/galaxy-dev/2016-August/024754.html
> Add 64-bit Linux binaries for mira 4.9.5

- urls.tsv
This fix will work around ATLAS_LIB_DIR not being set on OS X, since
Apple's veclib is being used.
```
(.venv)mariuss-MBP:fix_numpy marius$ diff -Nru numpy-1.9.2/setup.py
setup.py
--- numpy-1.9.2/setup.py    2016-03-07 12:40:02.000000000 +0100
+++ setup.py    2016-08-10 11:37:47.000000000 +0200
@@ -204,9 +204,9 @@
site_cfg.write("[atlas]\n"
"library_dirs = %s\n"
"include_dirs = %s\n"
-                           % (os.environ['ATLAS_LIB_DIR'],
-                              os.environ['ATLAS_INCLUDE_DIR']))
-    except Exception,ex:
+                           % (os.environ.get('ATLAS_LIB_DIR', ""),
+                              os.environ.get('ATLAS_INCLUDE_DIR', "")))
+    except Exception as ex:
raise RuntimeError("Writing custom site.cfg failed! %s" % ex)
```
Ping @bgruening
> Add numpy tarball with fix for OS X in setup.py

- urls.tsv
Cache the current latest MIRA development binaries, which I want to use from https://github.com/peterjc/galaxy_mira/blob/master/packages/package_mira_4_9_6/tool_dependencies.xml
Also recording the original URLs for MIRA 4.0.2 (still live) and MIRA 4.9.5 (defunct), which seem more useful than the ``/srv/nginx/...`` internal path which I assume was an implementation detail?
> Cache binaries for MIRA 4.9.6

- urls.tsv
Ping @bgruening.
rpy2 is in bioconda, but not singledispatch (which is just listed as a requirement), so we still need to add this to the cargoport, right?
> Add singledispatch (for rpy2)

- urls.tsv
Forgot to put this in a branch, but here is a tool for the cargo port. There is a bioconda recipe for it, but the original download page offers the same URL even if the pkg is updated (also the reason use_upstream is set to False here), so it would be good to have it versioned in the depot.
> Added MSGFPlus, MS/MS proteomics search tool

- urls.tsv
Note as of this release the Mac/Darwin binaries are x64 only.
```
$ shasum -a 256 ncbi-blast-2.5.0+-x64-*
d7006968b527fc151db9d6e58c3ad3235f0b04d9769dcb1a49f3eeb9303b84ac  ncbi-blast-2.5.0+-x64-linux.tar.gz
a446a18eec900cfd821a754bd984f6fe7076341801ece5ca40cbcddde7d0ca72  ncbi-blast-2.5.0+-x64-macosx.tar.gz
```
Source: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.5.0/
> Cache the NCBI BLAST+ 2.5.0 binaries

- urls.tsv
This is actually a JAVA program, thus following the existing convention we label this as source code suitable for all platforms (rather than a platform specific binary).
> Cache b2g4pipe_v2.5.zip (command line Blast2GO for pipelines)

- urls.tsv
I will be preparing a legacy ``tool_dependencies.xml`` package for the Tool Shed using this.
It is already in BioConda https://github.com/bioconda/bioconda-recipes/commit/d71b23f4988ab9a3c2914c7a478d50f520a85b85
> Cache NCBI BLAST+ 2.6.0 tar-balls for x86

- urls.tsv
The release of MetaPhlAn2 can not be downloaded anymore from BitBuckets (too big), which is an issue for BioConda and the data manager for MetaPhlAn2.
I cloned the repo, move to the tag version, create a tarball of the code and store it (temporarily) on my OwnCloud.
Bérénice
> Add 2.6.0 metaphlan2 version

- urls.tsv
I'm making another legacy IUC ToolShed package for BLAST+ 2.7.0 so for consistency would like the cache the source tar-balls here as previously.
Cross reference https://github.com/bioconda/bioconda-recipes/pull/6282 for the BioConda recipe for BLAST+ 2.7.0
> Cache NCBI BLAST+ 2.7.0 tar-balls for x86

- urls.tsv
Cross reference #134 for NCBI BLAST+ 2.7.0 which the NCBI later pulled in favour of this new BLAST+ 2.7.1 release.
> Cache NCBI BLAST+ 2.7.1 tar-balls for x86

- .ci/check.sh
- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
- CONTRIBUTING.md
- urls.tsv
for whatever reason some small errors were being silently ignored.
E.g.
- https://github.com/galaxyproject/cargo-port/pull/117 has a travis log which indicates that urls.tsv failed to validated but it marked it as success anyway.
> add default PR text + fix build to not ignore errors

- urls.tsv
This is pure Python 2.7 project, but bundles a 64-bit Linux pre-compiled binary (``tools/biocrf-static``), so I have marked the package as a whole as Linux x64.
The tool is under the GPL v3, and while the author seems receptive to using a repository in future,  the software currently only exists to the public as a tar-ball on an academic website:
https://deepsig.biocomp.unibo.it/deepsig/default/software
Once I know it is backed up here, I would be willing to try building a BioConda recipe for this.
> Cache deepsig-1.0.tar.gz

- urls.tsv
Their current home is somewhat stable but I would be more comfortable if they were stored by an official archive project.
The original source is https://www.uni-goettingen.de/en/research/185810.html. This site does not host its previous versions.
> Add Colombo 3.8 and 4.0

- .conda/get_meta.sh
- .conda/to_cargoport.py
- bin/process_urls.py
- cargoport/utils.py
This change makes it possible to verify against an MD5 hash instead of a SHA256. It also will automatically use MD5 hashes from bioconda recipes if a sha256 hash is not specified in the recipe. It will also refuse to download an archive if a hash is not provided in the TSV.
Automatic mirroring via Bioconda recipes is broken because the stored hash (an empty string) does not match the actual download's hash. At first I thought this was a problem only for Bioconductor packages because the current Bioconductor package recipes only include an md5 and not a sha256 in their `meta.yaml`s but then I discovered that the conda-to-cargo-port scripts [never actually write the sha256 hash](https://github.com/galaxyproject/cargo-port/blob/1464ad22dbdcb667aae11383bb3e8cdb20604cb9/.conda/to_cargoport.py#L …
> Support verifying md5 hashes in addition to sha256

- .conda/merge_dups.py
- .conda/run.sh
- .conda/to_cargoport.py
Some bioconda recipes today use aarch64/arm64 specific code, which needs to be handled.
Currently, no urls and checksums can be extracted for recipes like https://github.com/bioconda/bioconda-recipes/blob/master/recipes/vclust/meta.yaml.
> Distinguish more platforms and architectures

- .ci/run.sh
- bin/process_urls.py
This will handle bioconda urls correctly and persistently.
The old upgrade.sh code wiped out all checksum files before writing them freshly. This meant that checksums for older uploads could get lost. For bioconda packages, specifically, the old code had an error and wrote urls.tsv twice instead of writing them once followed by urls-bioconda.
> Generate checksum files during processing of urls
