galaxyproject/cargo-port

bin/process_urls.py

include ga tracking

---

urls.tsv

@bgruening This should include the additional column.

Add URL for meme 4.11.0

---

urls.tsv

added SVG-perl 2.63 for because it is a broken link in package_circos_0_67_5

added SVG-perl  2.63

---

urls.tsv

add R packages for trinity

---

urls.tsv

A new edgeR version for [#602](https://github.com/galaxyproject/tools-iuc/pull/602)

add edgeR 3.12

---

urls.tsv

for https://github.com/galaxyproject/tools-iuc/pull/618/files

add libmagic

---

urls.tsv

in preparation of new iuc package package_gnu_coreutils_8_25

Add coreutils 8.25 source

---

urls.tsv

For [trinity IUC PR](https://github.com/galaxyproject/tools-iuc/pull/602)

new version for biobase

---

urls.tsv

For [#648](https://github.com/galaxyproject/tools-iuc/pull/648)

Add stacks 1.40

---

urls.tsv

Add edger 3.14.0

---

urls.tsv

A new minor version for limma package

New limma version: 3.28.10

---

.ci/check.sh
bin/galaxy-cachefile-external-validator
bin/travis.py
cargoport/utils.py

Move silly bash one-liner that had outlived its usefulness into a proper script to handle a list of changes.

Fix 85, replace oneline with script for travis testing.

---

urls.tsv

Replaces original pull request #89 (which github didn't seem to let me reopen)

Protein analysis tools

---

urls.tsv

To sync iuc toolshed package with what's available in bioconda.

Fetch rpy2.2.7.8

---

urls.tsv

singledispatch is type src all

---

urls.tsv

Fix limma name and extension

---

urls.tsv

https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_bioconductor_limma_3_28_10/tool_dependencies.xml
😭

update limma-3.28.10 url

---

urls.tsv

adding conda deb package

---

bin/check.py
bin/dedup.py
bin/expected.py
bin/gsl.py
bin/merge_apis.py
bin/process_urls.py
bin/travis.py
bin/verify.py
cargoport/utils.py
requirements.txt
setup.py

Py3k Support

---

urls.tsv

new version with fixed tabular output mode

domclust v.1.2.8a

---

urls.tsv

Add pysam 64 bit linux wheels and source.

---

urls.tsv

NCBI Public domain software - from ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools/README.htm: 
> We make it freely available to the public without restriction to facilitate the use of NCBI by the scientific community
.

Add asn2gb binaries for mac and linux64

---

bin/check.py
bin/gsl.py

fix shebang to "#!/usr/bin/env python"

---

urls.tsv

See https://github.com/bioconda/bioconda-recipes/pull/7048#issuecomment-351171184
-  Apache 2.0 -> https://mvnrepository.com/artifact/org.apache.ant/ant-apache-bcel/1.8.1

Add ant build dependency BCEL for use in conda package

---

bin/check.py
urls.tsv

Correct spacing for packaging wheel entry.

---

urls.tsv

Add cfm-id 2.4

---

urls.tsv

Add readfq utility for high-speed reporting of fastq/fastq statistics

---

urls.tsv

- the sourceforge link deprecates after 1d
- needed here https://github.com/bernt-matthias/bioconda-recipes/tree/topic/cfmid-progress/recipes/cfm-id/

cfm: add cfm sources to cargo port

---

urls.tsv

needed for this one here: https://github.com/bioconda/bioconda-recipes/pull/16078

add a stable download for genform r8

---

urls.tsv

Add mauve 2015 snapshot

---

urls.tsv

for https://github.com/workflow4metabolomics/tools-metabolomics/pull/153
I guess license should be fine.

add genform/molgen manual

---

urls.tsv

in order to have a stable versioned link
Has apache2 license according to http://luciphor2.sourceforge.net/ .. is this fine?

add luciphor

---

bin/gsl.py
bin/process_urls.py
bin/verify.py
cargoport/utils.py

fix https://github.com/galaxyproject/cargo-port/issues/165
and remove a bit of code duplication

fix py3 urllib problem

---

urls.tsv

add luciphor2.1

---

urls.tsv

http://www.coxdocs.org/lib/exe/fetch.php?media=license_agreement.pdf
I double checked that the checksums of the download from the official site and the google drive match.

add maxquant 2.4.2.0

---

urls.tsv

2.4.9.0 was never deployed
xref https://github.com/bioconda/bioconda-recipes/pull/41221#issuecomment-1600427524

MaxQuant 2.4.9.0

---

urls.tsv

Update snpEff versions in urls.tsv

---

.conda/to_cargoport.py
bin/process_urls.py

Aim at using first source with matching checksum.

Try all urls in bioconda recipes
